class SuraModel {
  String suraNameEn;
  String suraNameAr;
  String suraNumOfVerses;

  SuraModel({
    required this.suraNameEn,
    required this.suraNameAr,
    required this.suraNumOfVerses,
  });

  static List<SuraModel> suras = [
    SuraModel( suraNameAr: "الفاتحه", suraNameEn: "Al-Fatiha", suraNumOfVerses: "7"),
    SuraModel( suraNameAr: "البقرة", suraNameEn: "Al-Baqarah", suraNumOfVerses: "286"),
    SuraModel( suraNameAr: "آل عمران", suraNameEn: "Aal-E-Imran", suraNumOfVerses: "200"),
    SuraModel( suraNameAr: "النساء", suraNameEn: "An-Nisa'", suraNumOfVerses: "176"),
    SuraModel( suraNameAr: "المائدة", suraNameEn: "Al-Ma'idah", suraNumOfVerses: "120"),
    SuraModel( suraNameAr: "الأنعام", suraNameEn: "Al-An'am", suraNumOfVerses: "165"),
    SuraModel( suraNameAr: "الأعراف", suraNameEn: "Al-A'raf", suraNumOfVerses: "206"),
    SuraModel( suraNameAr: "الأنفال", suraNameEn: "Al-Anfal", suraNumOfVerses: "75"),
    SuraModel( suraNameAr: "التوبة", suraNameEn: "At-Tawbah", suraNumOfVerses: "129"),
    SuraModel( suraNameAr: "يونس", suraNameEn: "Yunus", suraNumOfVerses: "109"),
    SuraModel( suraNameAr: "هود", suraNameEn: "Hud", suraNumOfVerses: "123"),
    SuraModel( suraNameAr: "يوسف", suraNameEn: "Yusuf", suraNumOfVerses: "111"),
    SuraModel( suraNameAr: "الرعد", suraNameEn: "Ar-Ra'd", suraNumOfVerses: "43"),
    SuraModel( suraNameAr: "إبراهيم", suraNameEn: "Ibrahim", suraNumOfVerses: "52"),
    SuraModel( suraNameAr: "الحجر", suraNameEn: "Al-Hijr", suraNumOfVerses: "99"),
    SuraModel( suraNameAr: "النحل", suraNameEn: "An-Nahl", suraNumOfVerses: "128"),
    SuraModel( suraNameAr: "الإسراء", suraNameEn: "Al-Isra", suraNumOfVerses: "111"),
    SuraModel( suraNameAr: "الكهف", suraNameEn: "Al-Kahf", suraNumOfVerses: "110"),
    SuraModel( suraNameAr: "مريم", suraNameEn: "Maryam", suraNumOfVerses: "98"),
    SuraModel( suraNameAr: "طه", suraNameEn: "Ta-Ha", suraNumOfVerses: "135"),
    SuraModel( suraNameAr: "الأنبياء", suraNameEn: "Al-Anbiya", suraNumOfVerses: "112"),
    SuraModel(suraNameAr: "الحج", suraNameEn: "Al-Hajj", suraNumOfVerses: "78"),
    SuraModel( suraNameAr: "المؤمنون", suraNameEn: "Al-Mu'minun", suraNumOfVerses: "118"),
    SuraModel( suraNameAr: "النّور", suraNameEn: "An-Nur", suraNumOfVerses: "64"),
    SuraModel( suraNameAr: "الفرقان", suraNameEn: "Al-Furqan", suraNumOfVerses: "77"),
    SuraModel( suraNameAr: "الشعراء", suraNameEn: "Ash-Shu'ara", suraNumOfVerses: "227"),
    SuraModel( suraNameAr: "النّمل", suraNameEn: "An-Naml", suraNumOfVerses: "93"),
    SuraModel( suraNameAr: "القصص", suraNameEn: "Al-Qasas", suraNumOfVerses: "88"),
    SuraModel( suraNameAr: "العنكبوت", suraNameEn: "Al-Ankabut", suraNumOfVerses: "69"),
    SuraModel( suraNameAr: "الرّوم", suraNameEn: "Ar-Rum", suraNumOfVerses: "60"),
    SuraModel( suraNameAr: "لقمان", suraNameEn: "Luqman", suraNumOfVerses: "34"),
    SuraModel( suraNameAr: "السجدة", suraNameEn: "As-Sajda", suraNumOfVerses: "30"),
    SuraModel( suraNameAr: "الأحزاب", suraNameEn: "Al-Ahzab", suraNumOfVerses: "73"),
    SuraModel( suraNameAr: "سبأ", suraNameEn: "Saba", suraNumOfVerses: "54"),
    SuraModel( suraNameAr: "فاطر", suraNameEn: "Fatir", suraNumOfVerses: "45"),
    SuraModel( suraNameAr: "يس", suraNameEn: "Ya-Sin", suraNumOfVerses: "83"),
    SuraModel( suraNameAr: "الصافات", suraNameEn: "As-Saffat", suraNumOfVerses: "182"),
    SuraModel(suraNameAr: "ص", suraNameEn: "Sad", suraNumOfVerses: "88"),
    SuraModel(suraNameAr: "الزمر", suraNameEn: "Az-Zumar", suraNumOfVerses: "75"),
    SuraModel( suraNameAr: "غافر", suraNameEn: "Ghafir", suraNumOfVerses: "85"),
    SuraModel( suraNameAr: "فصّلت", suraNameEn: "Fussilat", suraNumOfVerses: "54"),
    SuraModel( suraNameAr: "الشورى", suraNameEn: "Ash-Shura", suraNumOfVerses: "53"),
    SuraModel( suraNameAr: "الزخرف", suraNameEn: "Az-Zukhruf", suraNumOfVerses: "89"),
    SuraModel( suraNameAr: "الدّخان", suraNameEn: "Ad-Dukhan", suraNumOfVerses: "59"),
    SuraModel( suraNameAr: "الجاثية", suraNameEn: "Al-Jathiya", suraNumOfVerses: "37"),
    SuraModel( suraNameAr: "الأحقاف", suraNameEn: "Al-Ahqaf", suraNumOfVerses: "35"),
    SuraModel( suraNameAr: "محمد", suraNameEn: "Muhammad", suraNumOfVerses: "38"),
    SuraModel( suraNameAr: "الفتح", suraNameEn: "Al-Fath", suraNumOfVerses: "29"),
    SuraModel( suraNameAr: "الحجرات", suraNameEn: "Al-Hujurat", suraNumOfVerses: "18"),
    SuraModel( suraNameAr: "ق", suraNameEn: "Qaf", suraNumOfVerses: "45"),
    SuraModel( suraNameAr: "الذاريات", suraNameEn: "Adh-Dhariyat", suraNumOfVerses: "60"),
    SuraModel( suraNameAr: "الطور", suraNameEn: "At-Tur", suraNumOfVerses: "49"),
    SuraModel( suraNameAr: "النجم", suraNameEn: "An-Najm", suraNumOfVerses: "62"),
    SuraModel( suraNameAr: "القمر", suraNameEn: "Al-Qamar", suraNumOfVerses: "55"),
    SuraModel( suraNameAr: "الرحمن", suraNameEn: "Ar-Rahman", suraNumOfVerses: "78"),
    SuraModel( suraNameAr: "الواقعة", suraNameEn: "Al-Waqi'a", suraNumOfVerses: "96"),
    SuraModel( suraNameAr: "الحديد", suraNameEn: "Al-Hadid", suraNumOfVerses: "29"),
    SuraModel( suraNameAr: "المجادلة", suraNameEn: "Al-Mujadila", suraNumOfVerses: "22"),
    SuraModel( suraNameAr: "الحشر", suraNameEn: "Al-Hashr", suraNumOfVerses: "24"),
    SuraModel( suraNameAr: "الممتحنة", suraNameEn: "Al-Mumtahina", suraNumOfVerses: "13"),
    SuraModel( suraNameAr: "الصف", suraNameEn: "As-Saff", suraNumOfVerses: "14"),
    SuraModel( suraNameAr: "الجمعة", suraNameEn: "Al-Jumu'a", suraNumOfVerses: "11"),
    SuraModel( suraNameAr: "المنافقون", suraNameEn: "Al-Munafiqun", suraNumOfVerses: "11"),
    SuraModel( suraNameAr: "التغابن", suraNameEn: "At-Taghabun", suraNumOfVerses: "18"),
    SuraModel( suraNameAr: "الطلاق", suraNameEn: "At-Talaq", suraNumOfVerses: "12"),
    SuraModel( suraNameAr: "التحريم", suraNameEn: "At-Tahrim", suraNumOfVerses: "12"),
    SuraModel( suraNameAr: "الملك", suraNameEn: "Al-Mulk", suraNumOfVerses: "30"),
    SuraModel( suraNameAr: "القلم", suraNameEn: "Al-Qalam", suraNumOfVerses: "52"),
    SuraModel( suraNameAr: "الحاقة", suraNameEn: "Al-Haqqah", suraNumOfVerses: "52"),
    SuraModel( suraNameAr: "المعارج", suraNameEn: "Al-Ma'arij", suraNumOfVerses: "44"),
    SuraModel( suraNameAr: "نوح", suraNameEn: "Nuh", suraNumOfVerses: "28"),
    SuraModel( suraNameAr: "الجن", suraNameEn: "Al-Jinn", suraNumOfVerses: "28"),
    SuraModel( suraNameAr: "المزّمّل", suraNameEn: "Al-Muzzammil", suraNumOfVerses: "20"),
    SuraModel( suraNameAr: "المدّثر", suraNameEn: "Al-Muddathir", suraNumOfVerses: "56"),
    SuraModel( suraNameAr: "القيامة", suraNameEn: "Al-Qiyamah", suraNumOfVerses: "40"),
    SuraModel( suraNameAr: "الإنسان", suraNameEn: "Al-Insan", suraNumOfVerses: "31"),
    SuraModel( suraNameAr: "المرسلات", suraNameEn: "Al-Mursalat", suraNumOfVerses: "50"),
    SuraModel( suraNameAr: "النبأ", suraNameEn: "An-Naba'", suraNumOfVerses: "40"),
    SuraModel( suraNameAr: "النازعات", suraNameEn: "An-Nazi'at", suraNumOfVerses: "46"),
    SuraModel( suraNameAr: "عبس", suraNameEn: "Abasa", suraNumOfVerses: "42"),
    SuraModel( suraNameAr: "التكوير", suraNameEn: "At-Takwir", suraNumOfVerses: "29"),
    SuraModel( suraNameAr: "الإنفطار", suraNameEn: "Al-Infitar", suraNumOfVerses: "19"),
    SuraModel( suraNameAr: "المطفّفين", suraNameEn: "Al-Mutaffifin", suraNumOfVerses: "36"),
    SuraModel( suraNameAr: "الإنشقاق", suraNameEn: "Al-Inshiqaq", suraNumOfVerses: "25"),
    SuraModel( suraNameAr: "البروج", suraNameEn: "Al-Buruj", suraNumOfVerses: "22"),
    SuraModel( suraNameAr: "الطارق", suraNameEn: "At-Tariq", suraNumOfVerses: "17"),
    SuraModel( suraNameAr: "الأعلى", suraNameEn: "Al-A'la", suraNumOfVerses: "19"),
    SuraModel( suraNameAr: "الغاشية", suraNameEn: "Al-Ghashiyah", suraNumOfVerses: "26"),
    SuraModel( suraNameAr: "الفجر", suraNameEn: "Al-Fajr", suraNumOfVerses: "30"),
    SuraModel( suraNameAr: "البلد", suraNameEn: "Al-Balad", suraNumOfVerses: "20"),
    SuraModel( suraNameAr: "الشمس", suraNameEn: "Ash-Shams", suraNumOfVerses: "15"),
    SuraModel( suraNameAr: "الليل", suraNameEn: "Al-Lail", suraNumOfVerses: "21"),
    SuraModel( suraNameAr: "الضحى", suraNameEn: "Ad-Duha", suraNumOfVerses: "11"),
    SuraModel( suraNameAr: "الشرح", suraNameEn: "Ash-Sharh", suraNumOfVerses: "8"),
    SuraModel( suraNameAr: "التين", suraNameEn: "At-Tin", suraNumOfVerses: "8"),
    SuraModel( suraNameAr: "العلق", suraNameEn: "Al-Alaq", suraNumOfVerses: "19"),
    SuraModel( suraNameAr: "القدر", suraNameEn: "Al-Qadr", suraNumOfVerses: "5"),
    SuraModel( suraNameAr: "البينة", suraNameEn: "Al-Bayyina", suraNumOfVerses: "8"),
    SuraModel( suraNameAr: "الزلزلة", suraNameEn: "Az-Zalzalah", suraNumOfVerses: "8"),
    SuraModel( suraNameAr: "العاديات", suraNameEn: "Al-Adiyat", suraNumOfVerses: "11"),
    SuraModel( suraNameAr: "القارعة", suraNameEn: "Al-Qari'a", suraNumOfVerses: "11"),
    SuraModel( suraNameAr: "التكاثر", suraNameEn: "At-Takathur", suraNumOfVerses: "8"),
    SuraModel( suraNameAr: "العصر", suraNameEn: "Al-Asr", suraNumOfVerses: "3"),
    SuraModel( suraNameAr: "الهمزة", suraNameEn: "Al-Humazah", suraNumOfVerses: "9"),
    SuraModel( suraNameAr: "الفيل", suraNameEn: "Al-Fil", suraNumOfVerses: "5"),
    SuraModel( suraNameAr: "قريش", suraNameEn: "Quraysh", suraNumOfVerses: "4"),
    SuraModel( suraNameAr: "الماعون", suraNameEn: "Al-Ma'un", suraNumOfVerses: "7"),
    SuraModel( suraNameAr: "الكوثر", suraNameEn: "Al-Kawthar", suraNumOfVerses: "3"),
    SuraModel( suraNameAr: "الكافرون", suraNameEn: "Al-Kafirun", suraNumOfVerses: "6"),
    SuraModel( suraNameAr: "النصر", suraNameEn: "An-Nasr", suraNumOfVerses: "3"),
    SuraModel( suraNameAr: "المسد", suraNameEn: "Al-Masad", suraNumOfVerses: "5"),
    SuraModel( suraNameAr: "الإخلاص", suraNameEn: "Al-Ikhlas", suraNumOfVerses: "4"),
    SuraModel( suraNameAr: "الفلق", suraNameEn: "Al-Falaq", suraNumOfVerses: "5"),
    SuraModel( suraNameAr: "الناس", suraNameEn: "An-Nas", suraNumOfVerses: "6"),
  ];
}